name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Scan container image with Tenable Cloud Security
      uses: tenable/cloud-security-actions/container-image/scan@v1
      with:
        api-token: ${{ secrets.TENABLE_API_TOKEN }}
        api-url: https://sg.app.ermetic.com
        name: in0ri/defaced
